login:
    path: /login
    defaults: { _controller: ezpublish.security.controller:loginAction }

login_check:
    path: /login_check

logout:
    path: /logout

kernel.internal:
    resource: '@EzPublishCoreBundle/Resources/config/routing/internal.yml'

kernel.rest:
    resource: '@EzPublishRestBundle/Resources/config/routing.yml'
    prefix: '%ezpublish_rest.path_prefix%'

kernel.rest.options:
    resource: '@EzPublishRestBundle/Resources/config/routing.yml'
    prefix: '%ezpublish_rest.path_prefix%'
    type: rest_options

ezplatform.admin_ui:
    resource: '@EzPlatformAdminUiBundle/Resources/config/routing.yml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'

ezplatform.ee.page_builder:
    resource: '@EzPlatformPageBuilderBundle/Resources/config/routing.yml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'

_ezplatformRepositoryFormsRoutes:
    resource: '@EzSystemsRepositoryFormsBundle/Resources/config/routing.yml'

ezplatform.ee.dependencies.bazinga:
    resource: '@BazingaJsTranslationBundle/Resources/config/routing/routing.yml'

ezplatform.ee.fieldtype.page:
    resource: '@EzPlatformPageFieldTypeBundle/Resources/config/routing.yml'

ezplatform.ee.date_based_publisher:
    resource: '@EzSystemsDateBasedPublisherBundle/Resources/config/routing.yml'
    prefix: '%ez_systems_date_based_publisher_rest_prefix%'

ezplatform.ee.flex_workflow:
    resource: '@FlexWorkflowBundle/Resources/config/routing.yml'


fos.js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

# Custom redirection from /ez to /admin, feel free to adjust to your needs or remove if you don't need it
platform1_admin_route:
    path: /ez
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin
        permanent: true


# This file is auto-generated during the composer install
silversolutions_eshop:
    resource: "@SilversolutionsEshopBundle/Resources/config/ses_routing.yml"
    prefix: /
silversolutions_datatypes:
    resource: '@SilversolutionsDatatypesBundle/Resources/config/routing.yml'
    prefix: /
silversolutions_tools:
    resource: '@SilversolutionsToolsBundle/Resources/config/routing.yml'
    prefix: /
silversolutions_translation:
    resource: '@SilversolutionsTranslationBundle/Resources/config/routing.yml'
    prefix: /

siso_checkout:
    resource: '@SisoCheckoutBundle/Resources/config/routing.yml'
    prefix: /
siso_comparison:
    resource: '@SisoComparisonBundle/Resources/config/routing.yml'
    prefix: /
siso_quick_order:
    resource: '@SisoQuickOrderBundle/Resources/config/routing.yml'
    prefix: /
siso_search:
    resource: '@SisoSearchBundle/Resources/config/routing.yml'
    prefix: /
siso_tools:
    resource: '@SisoToolsBundle/Resources/config/routing.yml'
    prefix: /
#siso_voucher:
#    resource: "@SisoVoucherBundle/Resources/config/routing.yml"
#    prefix: /
siso_shop_price_engine:
    resource: "@ShopPriceEnginePluginBundle/Resources/config/routing.yml"
    prefix: /
#_siso_payment:
    #resource: '@SisoPaymentBundle/Resources/config/routing.yml'
#_siso_paypal_payment:
    #resource: '@SisoPaypalPaymentBundle/Resources/config/routing.yml'
siso_orderhistory:
    resource: '@SisoOrderHistoryBundle/Resources/config/routing.yml'
    prefix: /
