-
    type: reference
    mode: load
    file: 'var/migration/references.yml'
    overwrite: true

-
    type: role
    mode: create
    name: 'Ecommerce anonymous'
    policies:
        -
            module: content
            function: read
            limitations:
                - { identifier: Class, values: [article, file, folder, image, landing_page, ses_category, ses_product, ses_productcatalog, st_module, st_textmodule] }
                - { identifier: Section, values: [components, media, standard] }
        -
            module: user
            function: login
            limitations:
                - { identifier: SiteAccess, values: [site] }
        -
            module: siso_policy
            function: read_basket
            limitations: {  }
        -
            module: siso_policy
            function: write_basket
            limitations: {  }
        -
            module: siso_policy
            function: see_product_price
            limitations: {  }
        -
            module: siso_policy
            function: quickorder
            limitations: {  }
    assign:
        -
            type: group
            ids: [reference:ref_user_group__anonymous_users, reference:ref_user_group__shop_users]

-
    type: role
    mode: create
    name: 'Ecommerce checkout'
    policies:
        -
            module: siso_policy
            function: checkout
            limitations: {  }
    assign:
        -
            type: group
            ids: [reference:ref_user_group__anonymous_users, reference:ref_user_group__shop_users]

-
    type: role
    mode: create
    name: 'Ecommerce registered users'
    policies:
        -
            module: siso_policy
            function: edit_invoice
            limitations: {  }
        -
            module: siso_policy
            function: forms_profile_edit
            limitations: {  }
        -
            module: siso_policy
            function: order_list
            limitations: {  }
        -
            module: siso_policy
            function: edit_delivery
            limitations: {  }
    assign:
        -
            type: group
            ids: [reference:ref_user_group__shop_users]

-
    type: role
    mode: update
    match:
        identifier: 'Member'
    assign:
        -
            type: group
            ids: [reference:ref_user_group__shop_users]
